"""Changed inheritance of the DocumentCollectionAssociation class and fixed the call of datetime.now() functions to datetime.now

Revision ID: 2823240cec81
Revises: cfdd37e25d83
Create Date: 2025-06-07 19:51:57.679724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2823240cec81'
down_revision: Union[str, None] = 'cfdd37e25d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentCollection',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['Collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['Documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'collection_id', 'id')
    )
    op.create_index(op.f('ix_DocumentCollection_id'), 'DocumentCollection', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DocumentCollection_id'), table_name='DocumentCollection')
    op.drop_table('DocumentCollection')
    # ### end Alembic commands ###
