"""add cascade delete on loginmetric

Revision ID: 28b58775d0da
Revises: 044d2669fe2f
Create Date: 2025-06-07 17:28:58.934539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b58775d0da'
down_revision: Union[str, None] = '044d2669fe2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Login_metrics_user_id_fkey'), 'Login_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'Login_metrics', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Login_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('Login_metrics_user_id_fkey'), 'Login_metrics', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###
