"""Created associative table DocumentCollectionAssociation and fixed call of functions datetime.now() to datetime.now

Revision ID: 81dee9a3c1dd
Revises: cfdd37e25d83
Create Date: 2025-06-07 19:58:58.044091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81dee9a3c1dd'
down_revision: Union[str, None] = 'cfdd37e25d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentCollectionAssociation',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['Collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['Documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'collection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DocumentCollectionAssociation')
    # ### end Alembic commands ###
