"""Adding a Collection model, a constraint in Document.data(nullable=False), a relationship with a Collection model, an associative DocumentCollectionAssociation model

Revision ID: cfdd37e25d83
Revises: 8da1f1bebd4b
Create Date: 2025-06-07 19:31:17.471280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdd37e25d83'
down_revision: Union[str, None] = '8da1f1bebd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Collections',
    sa.Column('name_collection', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_collection')
    )
    op.create_index(op.f('ix_Collections_id'), 'Collections', ['id'], unique=False)
    op.create_index(op.f('ix_Collections_user_id'), 'Collections', ['user_id'], unique=False)
    op.create_index(op.f('ix_Documents_id'), 'Documents', ['id'], unique=False)
    op.create_index(op.f('ix_Documents_user_id'), 'Documents', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'Documents', ['name_file'])
    op.create_index(op.f('ix_Login_metrics_id'), 'Login_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_Login_metrics_user_id'), 'Login_metrics', ['user_id'], unique=False)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_index(op.f('ix_Login_metrics_user_id'), table_name='Login_metrics')
    op.drop_index(op.f('ix_Login_metrics_id'), table_name='Login_metrics')
    op.drop_constraint(None, 'Documents', type_='unique')
    op.drop_index(op.f('ix_Documents_user_id'), table_name='Documents')
    op.drop_index(op.f('ix_Documents_id'), table_name='Documents')
    op.drop_index(op.f('ix_Collections_user_id'), table_name='Collections')
    op.drop_index(op.f('ix_Collections_id'), table_name='Collections')
    op.drop_table('Collections')
    # ### end Alembic commands ###
