networks:
  prod_net:
    name: prod_net


volumes:
  postgres_data:

services:  
  postgres:
    image: postgres:15.4
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "tf_idf_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod_net
  
  app:
    build: .
    command: bash -c "alembic upgrade heads && python main.py"
    env_file:
      - .env
    volumes:
      - ./home/ubuntu/Web-app-for-analysis-TF-IDF/.env:/app/.env
    depends_on:
      - postgres
    networks:
      - prod_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api:
    build: .
    command: bash -c "python api.py"
    env_file:
      - .env
    volumes:
      - ./home/ubuntu/Web-app-for-analysis-TF-IDF/.env:/app/.env
    depends_on:
      - app
    networks:
      - prod_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5050/"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - api
    networks:
      - prod_net